name: release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle build
        run: ./gradlew build shadowJar

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Move,rename packages and get tag,version
        id: package
        run: |
          mkdir packages
          mv build/libs/*-all.jar packages/
          cd packages
          
          for file in `ls|grep .jar`
          do
            newfile=`echo $file | sed 's/-all//g'`
            echo $newfile
            mv $file $newfile
          done

          for file in `ls|grep .jar`
          do
            var1=`echo $file | sed 's/.jar//g'`
            break
          done
          var3=`expr index $var1 '.'`
          var2=${var1:0:$var3-1}
          var2=${var2%-*}+2
          var2=`expr length $var2`
          output=`expr substr $var1 $var2 $var3`
          echo "::set-output name=VERSION::$output"
          
      - name: Github release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.package.outputs.VERSION }}"
          prerelease: true
          title: "Bukkit Message Source ${{ steps.package.outputs.VERSION }}"
          files: |
            packages/*.jar
